## Server port configuration
server:
  port: 9010
#  error:
#      whitelabel:
#        enabled: false

## Spring Database configures by Datasource like MySql
Spring:
  datasource:
    name: product_services
    url: jdbc:mysql://localhost:3306/product_services
    username: root
    password: upreti
    driver-class-name: com.mysql.cj.jdbc.Driver
  Jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    hibernate.ddl-auto: update
    show-sql: false

#  mvn:
#    pathmatch:
#      matching-strategy: ANT_PATH_METCHER
    ## for spring security userName and password config
#  security:
#    user:
#      name: upreti
#      password: upreti
